<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/backend.proto
namespace Dudlewebs\WPMCS\GCP\Google\Api;

use Dudlewebs\WPMCS\GCP\Google\Protobuf\Internal\GPBType;
use Dudlewebs\WPMCS\GCP\Google\Protobuf\Internal\GPBUtil;
use Dudlewebs\WPMCS\GCP\Google\Protobuf\RepeatedField;
/**
 * `Backend` defines the backend configuration for a service.
 *
 * Generated from protobuf message <code>google.api.Backend</code>
 */
class Backend extends \Dudlewebs\WPMCS\GCP\Google\Protobuf\Internal\Message
{
    /**
     * A list of API backend rules that apply to individual API methods.
     * **NOTE:** All service configuration rules follow "last one wins" order.
     *
     * Generated from protobuf field <code>repeated .google.api.BackendRule rules = 1;</code>
     */
    private $rules;
    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Api\BackendRule[] $rules
     *           A list of API backend rules that apply to individual API methods.
     *           **NOTE:** All service configuration rules follow "last one wins" order.
     * }
     */
    public function __construct($data = NULL)
    {
        \Dudlewebs\WPMCS\GCP\GPBMetadata\Google\Api\Backend::initOnce();
        parent::__construct($data);
    }
    /**
     * A list of API backend rules that apply to individual API methods.
     * **NOTE:** All service configuration rules follow "last one wins" order.
     *
     * Generated from protobuf field <code>repeated .google.api.BackendRule rules = 1;</code>
     * @return RepeatedField<\Google\Api\BackendRule>
     */
    public function getRules()
    {
        return $this->rules;
    }
    /**
     * A list of API backend rules that apply to individual API methods.
     * **NOTE:** All service configuration rules follow "last one wins" order.
     *
     * Generated from protobuf field <code>repeated .google.api.BackendRule rules = 1;</code>
     * @param \Google\Api\BackendRule[] $var
     * @return $this
     */
    public function setRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Dudlewebs\WPMCS\GCP\Google\Protobuf\Internal\GPBType::MESSAGE, \Dudlewebs\WPMCS\GCP\Google\Api\BackendRule::class);
        $this->rules = $arr;
        return $this;
    }
}
