<?php

namespace Dudlewebs\WPMCS\GCP;

// autoload_real.php @generated by Composer
class ComposerAutoloaderInitc7fca8378911e90fd12b2769406f6100
{
    private static $loader;
    public static function loadClassLoader($class)
    {
        if ('Dudlewebs\\WPMCS\\GCP\\Composer\\Autoload\\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }
    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }
        require __DIR__ . '/platform_check.php';
        \spl_autoload_register(array('Dudlewebs\\WPMCS\\GCP\\ComposerAutoloaderInitc7fca8378911e90fd12b2769406f6100', 'loadClassLoader'), \true, \true);
        self::$loader = $loader = new \Dudlewebs\WPMCS\GCP\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        \spl_autoload_unregister(array('Dudlewebs\\WPMCS\\GCP\\ComposerAutoloaderInitc7fca8378911e90fd12b2769406f6100', 'loadClassLoader'));
        require __DIR__ . '/autoload_static.php';
        \call_user_func(\Dudlewebs\WPMCS\GCP\Composer\Autoload\ComposerStaticInitc7fca8378911e90fd12b2769406f6100::getInitializer($loader));
        $loader->setClassMapAuthoritative(\true);
        $loader->register(\true);
        $filesToLoad = \Dudlewebs\WPMCS\GCP\Composer\Autoload\ComposerStaticInitc7fca8378911e90fd12b2769406f6100::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = \true;
                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }
        return $loader;
    }
}
