<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/error_details.proto
namespace Dudlewebs\WPMCS\Google\Rpc;

use Dudlewebs\WPMCS\Google\Protobuf\Internal\GPBType;
use Dudlewebs\WPMCS\Google\Protobuf\Internal\GPBUtil;
use Dudlewebs\WPMCS\Google\Protobuf\RepeatedField;
/**
 * Provides links to documentation or for performing an out of band action.
 * For example, if a quota check failed with an error indicating the calling
 * project hasn't enabled the accessed service, this can contain a URL pointing
 * directly to the right place in the developer console to flip the bit.
 *
 * Generated from protobuf message <code>google.rpc.Help</code>
 */
class Help extends \Dudlewebs\WPMCS\Google\Protobuf\Internal\Message
{
    /**
     * URL(s) pointing to additional information on handling the current error.
     *
     * Generated from protobuf field <code>repeated .google.rpc.Help.Link links = 1;</code>
     */
    private $links;
    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Rpc\Help\Link[] $links
     *           URL(s) pointing to additional information on handling the current error.
     * }
     */
    public function __construct($data = NULL)
    {
        \Dudlewebs\WPMCS\GPBMetadata\Google\Rpc\ErrorDetails::initOnce();
        parent::__construct($data);
    }
    /**
     * URL(s) pointing to additional information on handling the current error.
     *
     * Generated from protobuf field <code>repeated .google.rpc.Help.Link links = 1;</code>
     * @return RepeatedField<\Google\Rpc\Help\Link>
     */
    public function getLinks()
    {
        return $this->links;
    }
    /**
     * URL(s) pointing to additional information on handling the current error.
     *
     * Generated from protobuf field <code>repeated .google.rpc.Help.Link links = 1;</code>
     * @param \Google\Rpc\Help\Link[] $var
     * @return $this
     */
    public function setLinks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Dudlewebs\WPMCS\Google\Protobuf\Internal\GPBType::MESSAGE, \Dudlewebs\WPMCS\Google\Rpc\Help\Link::class);
        $this->links = $arr;
        return $this;
    }
}
